server:
  port: 8070
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:file:./auth_db;AUTO_SERVER=TRUE;NON_KEYWORDS=USER;
    username: auth
    password: auth
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
      mode: always


