spring:
  application:
    name: affable-bean-backend-service
  datasource:
    url: jdbc:mysql://localhost:3306/affable_backend
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8099

